namespace IoTControllerContracts
{
    /// <summary>
    /// Represents a controller for appliances.
    /// </summary>
    public interface IApplianceController : IController
    {
        /// <summary>
        /// Adds a device to the controller.
        /// </summary>
        /// <param name="id"> The id generated by the database for the device </param>
        /// <returns> The added device if successful, null otherwise </returns>
        Task<IAppliance?> AddDeviceAsync(int id);

        /// <summary>
        /// Adds a device to the controller with a configuration.
        /// </summary>
        /// <param name="id"> The id generated by the database for the device </param>
        /// <param name="configuration"> The configuration for the device </param>
        /// <returns> The added device if successful, null otherwise </returns>
        Task<IAppliance?> AddDeviceWithConfigAsync(int id, string configuration);
    }
}
