using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IoTControllerContracts
{
    /// <summary>
    /// Represents a battery controller that can control batteries.
    /// </summary>
    public interface IBatteryController : IController
    {
        /// <summary>
        /// Adds a battery to the controller.
        /// </summary>
        /// <param name="id"> The id generated by the database for the battery </param>
        /// <returns> The added battery if successful, null otherwise </returns>
        Task<IBattery?> AddDeviceAsync(int id);

        /// <summary>
        /// Adds a battery to the controller with a configuration.
        /// </summary>
        /// <param name="id"> The id generated by the database for the battery </param>
        /// <param name="configuration"> The configuration for the battery </param>
        /// <returns> The added battery if successful, null otherwise </returns>
        Task<IBattery?> AddDeviceWithConfigAsync(int id, string configuration);
    }
}
